### ISSUE TITLE
Red Text in Files 

### ISSUE THREAD

**Issue by maxmehlbaum** [flypaper0/ethereum-wallet#10]
![screen shot 2018-02-13 at 10 44 37 pm](https://user-images.githubusercontent.com/23129188/36186872-c537bfb6-110f-11e8-8644-f51a25477c8d.png)
![screen shot 2018-02-13 at 10 44 34 pm](https://user-images.githubusercontent.com/23129188/36186873-c5cc9906-110f-11e8-8192-c688982b02c0.png)
![screen shot 2018-02-13 at 10 44 30 pm](https://user-images.githubusercontent.com/23129188/36186875-c8cbacfa-110f-11e8-9d7b-f5f53623406f.png)
![screen shot 2018-02-13 at 10 44 24 pm](https://user-images.githubusercontent.com/23129188/36186876-c9c611c2-110f-11e8-8f92-316ebeb548fd.png)

**Comment by flypaper0** [comment]
@maxmehlbaum it just an empty folders. To build: 
1) Clone repo or download zip
2) go to project folder in terminal
3) install pods (pod install)
4) app successfully start

**Comment by flypaper0** [comment]
Removed empty folders: Managers, Send, External
