### ISSUE TITLE
Crashed during import

### ISSUE THREAD

**Issue by uiharu-s** [flypaper0/ethereum-wallet#11]
I imported my keystore file from iCloud/files (specifically I accessed my file on Mega)
Conicoin seemed to load the file fine and prompted for password.
However, the app crashed and exited once I press "Done" upon entering password.
Welcome screen shows when I opened Conicoin again, so I tried to import again.

Intriguingly, just before I was going to give up after a few tries, I selected ~~restore from backup phrase~~ "Restore with passphrase" (which now replaced the "new wallet" button) instead this time. It prompted me for my password straight away. I entered, and my wallet has been successfully restored!

**Comment by flypaper0** [comment]
@uiharu-s I'll try to reproduce. This is epic, thanks for publishing

**Comment by uiharu-s** [comment]
I wonder if it's because my keystore was created with a desktop client that's very outdated (version 0.8.9) and out of sync (pre ETC fork).

So I created a new wallet with my desktop client that reproduces the issue (for me). Here it is in case it's helpful :)

[UTC--2018-03-06T18-54-00.217384000Z--1d0e422dfa609d6d06a75828e57093e35ea78a80.zip](https://github.com/flypaper0/ethereum-wallet/files/1786341/UTC--2018-03-06T18-54-00.217384000Z--1d0e422dfa609d6d06a75828e57093e35ea78a80.zip)
password: conicoin

**Comment by flypaper0** [comment]
fixed in release 2.0
