### ISSUE TITLE
Cannot "Exit wallet"

### ISSUE THREAD

**Issue by uiharu-s** [flypaper0/ethereum-wallet#12]
Returns "could not decrpyt key with given passphrase" even if I provided the correct passphrase.

**Comment by flypaper0** [comment]
@uiharu-s strange, this part I carefully tested. Exporting give the same error?

**Comment by uiharu-s** [comment]
My bad: most likely because I've never exported/"backup wallet" :p

I just tried again. First doing backup and then exit. Works as expected :D
