### ISSUE TITLE
How about the app size?

### ISSUE THREAD

**Issue by beyonderyue** [flypaper0/ethereum-wallet#14]
I know the geth for iOS is very large...
So can you tell me the size of your app?
Thank you

**Comment by flypaper0** [comment]
@beyonderyue Version from AppStore - 39,5 Mb

**Comment by beyonderyue** [comment]
395 Mb or 39.5 Mb ? If it's 39.5 Mb, it's good news.

**Comment by flypaper0** [comment]
@beyonderyue  39.5
