### ISSUE TITLE
May Swift 4 case the Int64 problem

### ISSUE THREAD

**Issue by bc1pjerry** [flypaper0/ethereum-wallet#15]
In GasService.swift file, line 35 missing argument for parameter "gas".

There are 5 errors in TransactionFactory.swift file.

`gethGasLimit?.setString(info.gasLimit.toHex(), base: 16)` 
should use non-optional value of type Int.

` return GethNewTransaction(noncePointer, gethAddress, intAmount, gethGasLimit, gethGasPrice, nil)`Cannot convert value of type 'Int' to expected argument type 'Int64', should replace with`'gethGasLimit' with 'Int64(gethGasLimit)'`

And there are two major problem with `let gethGasLimit: Int = extractedExpr`Cannot convert value of type 'GethBigInt!' to specified type 'Int'

` return GethNewTransaction(nonce, to, fakeAmount, gasLimit, gasPrice, data)`Cannot convert value of type 'GethBigInt?' to expected argument type 'Int64'

I don't know this just show on my xcode version or commit problems

**Comment by flypaper0** [comment]
@HangyuYe it happened after the Geth update to a newer version. Specify the version 1.7.3 in the Podfile. ` pod 'Geth', '~> 1.7.3'` and run `pod install` in terminal

**Comment by flypaper0** [comment]
close due to inactivity
