### ISSUE TITLE
genesis block and boot node

### ISSUE THREAD

**Issue by jaramburu** [flypaper0/ethereum-wallet#2]
Thanks for developing this! Where in the Xcode project is the genesis block located? Is there a way to specify a bootnode to use this on a private blockchain?

**Comment by flypaper0** [comment]
@jaramburu Hey, thanks for you response. You can find genesis in rinkeby.json in Other folder. Sorry, but I didn't try to run this on private blockchain. Planning to do that, because now it takes so long time to sync all blocks. If there is any information I will share with pleasure

**Comment by jaramburu** [comment]
Thanks! Do you know where to specify bootnode?

**Comment by flypaper0** [comment]
@jaramburu look at startNode() method in EthereumCore.swift

**Comment by jaramburu** [comment]
Thanks! Here is how I modified that method (my enode and IP address are redacted). It's throwing an error on line 88 "let genesis= try!..." Any idea what I'm doing wrong?

`extension Ethereum {
    
    fileprivate func startNode() throws {
        
        var error: NSError?
        let bootNodes = GethNewEnodesEmpty()
        bootNodes?.append(GethNewEnode("enode://enodeAddress@ipAddress", &error))
        
        let genesisPath = Bundle.main.path(forResource: "private", ofType: "json")
        let genesis = try! String(contentsOfFile: genesisPath!, encoding: String.Encoding.utf8)
        
        let config = GethNewNodeConfig()
        config?.setBootstrapNodes(bootNodes)
        config?.setEthereumGenesis(genesis)
        config?.setEthereumNetworkID(4)
        config?.setEthereumNetStats("flypaper:Respect my authoritah!@stats.rinkeby.io")
        
        let datadir = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
        ethereumNode = GethNewNode(datadir + "/.private", config, &error)
        
        try ethereumNode.start()
        
        if let error = error {
            throw EthereumError.nodeStartFailed(error: error)
        }
    }`

**Comment by jaramburu** [comment]
never mind I figured out my issue. genesispath needs to be 'rinkeby.' I'm now synced to my private chain. Thanks for the great work! Any plans to add more functionality (i.e. transactions)?

**Comment by flypaper0** [comment]
@jaramburu already add receiving, and start working on sending
