### ISSUE TITLE
pong timeout private network

### ISSUE THREAD

**Issue by jaramburu** [flypaper0/ethereum-wallet#3]
I was able to configure correctly to join my private blockchain, but I get a pong error when the light client tries to connect. Any suggestions? 

msg="<-readResp: response {\"jsonrpc\":\"2.0\",\"id\":1,\"result\":\"0x629e6882c8995ab2e46fa99bcf719eba\"}"
TRACE[10-24|13:53:50]                                          msg="--- (0) pongTimeout for 21b67f06bed42d56@104.197.143.226:30304: verifyinit -> unknown (ok)"

**Comment by jaramburu** [comment]
I think I need to call admin.addPeer("enode...) from the light client to force it to join the boot node on my private network. Any idea how to do that in Xcode?

**Comment by flypaper0** [comment]
Try this: 

```
var error: NSError?
    let bootNodes = GethNewEnodesEmpty()
    bootNodes?.append(GethNewEnode("enode...{HERE IS YOUR ENODE}", &error))
```

and after configuring node just start it. 

You run you private blockchain ethereum-core client?

**Comment by jaramburu** [comment]
I think that's how I have it configured currently (I masked my actual node and ip address and pasted my code below). Yes I'm running a private blockchain on a remote geth mining node. The enode and ip are for the main geth mining node. From what I can find online the lightweight client still needs to call admin.addPeer from the cli to join the private blockchain. Any idea how to do this (and to make other calls from the cli like send)?

`var error: NSError?
        let bootNodes = GethNewEnodesEmpty()
        bootNodes?.append(GethNewEnode("enode://21b67f06bed42d5625ba246a8235803f270db21ad578104863176471c8d0c4111ddef2a08b7af821d3581@1.1.1.1:30303?discport=30304", &error))`

**Comment by flypaper0** [comment]
If you do this on the simulator, try on the device. It is also necessary to specify the parameters of the node such as Genesis, networkId and NetStats. Unfortunately this is all that I can advise as I have not tried to set up a private block

```
    config?.setEthereumGenesis(genesis)
    config?.setEthereumNetworkID(4)
    config?.setEthereumNetStats("flypaper:Respect my authoritah!@stats.rinkeby.io")
```

**Comment by flypaper0** [comment]
close because of inactivity
