### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ceased-ebc** [flypaper0/ethereum-wallet#4]
Looks nice, A) is it operational?, B) Does it support ERC20 tokens?,

**Comment by flypaper0** [comment]
Hey, thanks. Now app on the apple review, I'll update readme when it's come to App Store. ERC20, in next release.

**Comment by grudev** [comment]
Do Apple actually approve ERC20 apps on App Store? I mean i have an app that just rewards the user some small quantities of crypto currency based on ERC20 token and doesn't even hold or actually transfer the reward. This is done by hand from administrator on a backend, and Apple still don't want to approve the app saying that violates "Guideline 3.1.5 - Business - Payments - Physical Goods and Services Outside of the App"

**Comment by flypaper0** [comment]
@grudev rejected binary or AppStore page meta? Strangely, this should not be a problem if your ERC20 tokens do not represent any calculated value. Try to prove it

**Comment by flypaper0** [comment]
close because of inactivity

**Comment by flypaper0** [comment]
close because of inactivity
