### ISSUE TITLE
How to create ERC20 token transaction?

### ISSUE THREAD

**Issue by Christopher-Cho** [flypaper0/ethereum-wallet#5]
Hi!
I am very thank you for your code.
I am a student that have interest about Ethereium.
I want to develop my wallet app, and your github is so helpful for me.

But, I wonder How to create ERC20 token transaction.
I want to my own ERC20 token, but Geth mudule don't have any API about ERC20.
Have any reference or knowledge?

Thank you!

**Comment by flypaper0** [comment]
@Christopher-Cho  Hey, thanks! Just pushed v1.1.1 with erc20 support

**Comment by Christopher-Cho** [comment]
Oh, Thank you!
