### ISSUE TITLE
Sent 1000 of Homemade ERC20 and received .000000000000001 Coin

### ISSUE THREAD

**Issue by maxmehlbaum** [flypaper0/ethereum-wallet#9]
i think either when i deployed the ERC20 i had 0 decimal places so this could of played a part in it. Or the interface only accepts fractions related to ETH/YOURERC20?? I chose 0 decimal places because when i would do more than that my total supply would go down by a digit based relative to the amount of decimal places i added. i.e 1000 total supply with a decimal of 2 would deposit 10.00 coins into my wallet. So my question is where does the 990 coins go. Is that whats left in the admin page i can just send the rest to myself or are they just gone and i have to restructure the code to take this error in to account?

Thoughts?

**Comment by flypaper0** [comment]
@maxmehlbaum thanks creating issue. Could you please tap on transaction in history tab and share me etherscan link?

**Comment by flypaper0** [comment]
@maxmehlbaum is it mainnet?

**Comment by maxmehlbaum** [comment]
Yeah the only way you can send ERC20 is through the mainnet. I tried my mist wallet to and it send whole amounts
________________________________

**Comment by flypaper0** [comment]
@maxmehlbaum ok tomorrow I'll check it out. Most likely an error displaying the transfer amount

**Comment by maxmehlbaum** [comment]
beautiful wallet btw

**Comment by maxmehlbaum** [comment]
![blipcoin](https://user-images.githubusercontent.com/23129188/36186403-dccf25c2-110c-11e8-8dab-35ec864148c1.png)

heres the screenshot

heres the link to the etherscan

https://etherscan.io/tx/0xc7d782bca549d5748d7ff58cb0015c0273bb68b4478821002fa1f078e3e5477d

**Comment by maxmehlbaum** [comment]
![screen shot 2018-02-13 at 10 28 30 pm](https://user-images.githubusercontent.com/23129188/36186473-445c0f34-110d-11e8-9956-fca053c40845.png)


as you can see on the block explorer and on the when I sent it another account on my mis wallet it shows up properly on mist but not on the mobile wallet

**Comment by maxmehlbaum** [comment]
also why are u using kingfisher, Is it for the QR code on the camera I'm looking through the code and trying to figure out why you would need image cacheing in the app?

**Comment by flypaper0** [comment]
@maxmehlbaum yes, you right, it is a balance displaying bug. Money transferred correctly. Kingfisher using for Token avatar images, but unfortunately not all tokens have that avatar

**Comment by uiharu-s** [comment]
Thank you for your beautiful work :D
I also encountered similar problem with DGD.
I have 1DGD in my wallet but Conicoin displays 0.000000001 DGD

**Comment by flypaper0** [comment]
@maxmehlbaum Hi, sorry for big pause, worked on second release. Now I'm trying to reproduce that bug. If it's possible, could you please send me some of your test erc20 tokens that caused this problem? My test mainnet address is 0x8c8cc09addf50fc01e4b75a0cf34da37e216b2e7

**Comment by flypaper0** [comment]
fixed in release 2.0
